apiVersion: v1
kind: Secret
metadata:
  name: bank-backend-secret
type: Opaque
stringData:
  DB_USERNAME: admin
  DB_PASSWORD: Cohort5Pod12


## echo -n "root" | base64
## echo -n "password123ABC" | base64
